// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXyDVT4pGDpynHPLdNIUjlqpffm8cieb0',
    appId: '1:181276302303:web:efd73358fd02c97145026a',
    messagingSenderId: '181276302303',
    projectId: 'rabbe3-ddad8',
    authDomain: 'rabbe3-ddad8.firebaseapp.com',
    storageBucket: 'rabbe3-ddad8.appspot.com',
    measurementId: 'G-JZZ0LEHVNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkCbtubpuuzioJGtWwQ6jHInlv7otfN4',
    appId: '1:181276302303:android:3e10d1dd8f88690f45026a',
    messagingSenderId: '181276302303',
    projectId: 'rabbe3-ddad8',
    storageBucket: 'rabbe3-ddad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJi5GyIJSb25FflPm_sNejwBflNdQEqPY',
    appId: '1:181276302303:ios:7ae6ce0f2d61af7f45026a',
    messagingSenderId: '181276302303',
    projectId: 'rabbe3-ddad8',
    storageBucket: 'rabbe3-ddad8.appspot.com',
    iosBundleId: 'com.example.fRabe3na',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJi5GyIJSb25FflPm_sNejwBflNdQEqPY',
    appId: '1:181276302303:ios:be50f5210270238c45026a',
    messagingSenderId: '181276302303',
    projectId: 'rabbe3-ddad8',
    storageBucket: 'rabbe3-ddad8.appspot.com',
    iosBundleId: 'com.example.fRabe3na.RunnerTests',
  );
}
